### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by A354-PH** [korado531m7/GrapplingHook#1]
[04:38:45] [Server thread/CRITICAL]: ErrorException: "Undefined property: korado531m7\GrapplingHook\FishingHook::$random" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 2223

I use PMMP 3.5.6

**Comment by A354-PH** [comment]
When I press fish, it throws the rod then I press the fish again then It shows that error

**Comment by korado531m7** [comment]
ok.
well, what version did you use?

i need more infomation

**Comment by A354-PH** [comment]
PMMP 3.5.6

**Comment by korado531m7** [comment]
sorry, plugin version

**Comment by A354-PH** [comment]
The one on poggit

**Comment by korado531m7** [comment]
ok. i'll check and fix if i am free
thank you
