### ISSUE TITLE
Kicks player

### ISSUE THREAD

**Issue by ManiakMCPE** [korado531m7/GrapplingHook#2]
With the latest version of PMMP, this plugin now kicks the player when they try to use the grappling hook.

08.02 18:24:49 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2496): korado531m7\GrapplingHook\FishingRod->onClickAir(pocketmine\Player object, pocketmine\math\Vector3 object)
08.02 18:24:49 [Server] Server thread/DEBUG #2 plugins/GrapplingHook.phar/src/korado531m7/GrapplingHook/FishingRod(57): pocketmine\entity\Entity::createEntity(string FishingHook, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object, pocketmine\Player object)
08.02 18:24:49 [Server] Server thread/DEBUG #1 src/pocketmine/entity/Entity(328): korado531m7\GrapplingHook\FishingHook->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object, pocketmine\Player object)
08.02 18:24:49 [Server] Server thread/DEBUG #0 plugins/GrapplingHook.phar/src/korado531m7/GrapplingHook/FishingHook(43): pocketmine\entity\Entity->__set(string random, pocketmine\utils\Random object)
08.02 18:24:49 [Server] Server thread/CRITICAL ErrorException: "Undefined property: korado531m7\GrapplingHook\FishingHook::$random" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 2223

**Comment by korado531m7** [comment]
thank you for reporting.
i'll fix it.

**Comment by korado531m7** [comment]
i tested and  i found that you must use latest version of this plugin.
